// Generated by psc-bundle 0.8.0.0
var PS = { };
(function(exports) {
  "use strict";

  // module Projections

  exports.when = function(eventname) {
    return function(eventhandler){
      var obj = {};
      obj[eventname] = function(state, event) {
        return eventhandler(state)(event);
      }
      return obj;
    };
  };

  exports.whenAny = function(eventhandler) {
    return {$any : function(s,e) {
      return eventhandler(s)(e);
    }};
  };

  exports.runProjection = function(eventSource){
    return function(initialState){
      return function(folder){
        var handlers = mergeObjects({$init: function(){return initialState;}},folder);
        return function() {
          getEventsource(eventSource).when(handlers);
        }
      }
    }
  }

  var getEventsource = function (eventSource) {
    if(isEventsourcetype(eventSource, exports.FromStream)){
      return fromStream(eventSource.value0);
    } else if(isEventsourcetype(eventSource, exports.FromStreams)){
      return fromStreams(eventSource.value0);
    } else if(isEventsourcetype(eventSource, exports.ForEachInCategory)){
      return fromCategory(eventSource.value0).foreachStream();
    } 
    return fromAll();
  }

  var mergeObjects = function (obj1,obj2){
    var obj3 = {};
    for (var attrname in obj1) { obj3[attrname] = obj1[attrname]; }
    for (var attrname2 in obj2) { obj3[attrname2] = obj2[attrname2]; }
    return obj3;
  }

  var isEventsourcetype = function(eventsource, expectedType) {
    return eventsource !== undefined && eventsource instanceof expectedType;
  }
 
})(PS["Projections"] = PS["Projections"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var $foreign = PS["Projections"];
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];     
  var FromStream = (function () {
      function FromStream(value0) {
          this.value0 = value0;
      };
      FromStream.create = function (value0) {
          return new FromStream(value0);
      };
      return FromStream;
  })();
  var FromAll = (function () {
      function FromAll() {

      };
      FromAll.value = new FromAll();
      return FromAll;
  })();
  var ForEachInCategory = (function () {
      function ForEachInCategory(value0) {
          this.value0 = value0;
      };
      ForEachInCategory.create = function (value0) {
          return new ForEachInCategory(value0);
      };
      return ForEachInCategory;
  })();
  var FromStreams = (function () {
      function FromStreams(value0) {
          this.value0 = value0;
      };
      FromStreams.create = function (value0) {
          return new FromStreams(value0);
      };
      return FromStreams;
  })();                                                              
  var fromStreams = function (streams) {
      return new FromStreams(streams);
  };
  var fromStream = function (streamname) {
      return new FromStream(streamname);
  };
  var fromAll = FromAll.value;
  var forEachInCategory = function (category) {
      return new ForEachInCategory(category);
  };
  exports["FromStream"] = FromStream;
  exports["FromAll"] = FromAll;
  exports["ForEachInCategory"] = ForEachInCategory;
  exports["FromStreams"] = FromStreams;
  exports["fromStreams"] = fromStreams;
  exports["forEachInCategory"] = forEachInCategory;
  exports["fromAll"] = fromAll;
  exports["fromStream"] = fromStream;
  exports["whenAny"] = $foreign.whenAny;
  exports["when"] = $foreign.when;
  exports["runProjection"] = $foreign.runProjection;;
 
})(PS["Projections"] = PS["Projections"] || {});
(function(exports) {
  // Generated by psc version 0.8.0.0
  "use strict";
  var Prelude = PS["Prelude"];
  var Control_Monad_Eff = PS["Control.Monad.Eff"];
  var Projections = PS["Projections"];     
  var handlerB = function (s) {
      return function (e) {
          return {
              count: s.count + 1 | 0
          };
      };
  };
  var handlerA = function (s) {
      return function (e) {
          return {
              count: s.count + 1 | 0
          };
      };
  };
  var whenAnyEvent = Projections.runProjection(Projections.fromAll)({
      count: 0
  })(Projections.whenAny(handlerA));
  var main = whenAnyEvent;
  var fromStreamsProjections = Projections.runProjection(Projections.fromStreams([ "$stats-127.0.0.1:2113", "$projections-$master" ]))({
      count: 0
  })(Projections.when("$statsCollected")(handlerA));
  var fromStreamProjections = Projections.runProjection(Projections.fromStream("$stats-127.0.0.1:2113"))({
      count: 0
  })(Projections.when("$statsCollected")(handlerA));
  var fromAllProjections = Projections.runProjection(Projections.fromAll)({
      count: 0
  })(Projections.when("$statsCollected")(handlerA));
  var forEachInCategoryProjections = Projections.runProjection(Projections.forEachInCategory("$stats"))({
      count: 0
  })(Projections.when("$statsCollected")(handlerA));
  exports["main"] = main;
  exports["whenAnyEvent"] = whenAnyEvent;
  exports["fromStreamsProjections"] = fromStreamsProjections;
  exports["forEachInCategoryProjections"] = forEachInCategoryProjections;
  exports["fromStreamProjections"] = fromStreamProjections;
  exports["fromAllProjections"] = fromAllProjections;
  exports["handlerB"] = handlerB;
  exports["handlerA"] = handlerA;;
 
})(PS["Main"] = PS["Main"] || {});

PS["Main"].main();
